#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
    selected=$1
else
    # selected=$(find /home ~/work ~/projects ~/ ~/usc ~/.config -mindepth 1 -maxdepth 1 -type d | fzf)
    # Find commands and escape spaces in results
    # Remove /.git and /.ts-anchor from find results
    main_dirs=$(find /home ~/ ~/usc ~/github-runners ~/.config -mindepth 1 -maxdepth 1 -type d | sed 's/ /\\ /g')
    git_dirs=$(find ~/usc ~/projects ~/work \( \( -type d -name ".git" \) -or \( -type f -name ".ts-anchor" \) \) | sed 's/ /\\ /g; s/\/\.git$//g; s/\/\.ts-anchor$//g')

    # Concat both lists of directories
    # Split them by any spaces with xargs -n1
    # Fuzzy find them
    selected=$(echo $main_dirs $git_dirs | xargs -n1 | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s $selected_name -c $selected
    exit 0
fi

if ! tmux has-session -t=$selected_name 2> /dev/null; then
    tmux new-session -ds $selected_name -c $selected
fi

tmux switch-client -t $selected_name
